spring:
  datasource:
    url: jdbc:mysql://192.168.73.7:3306/devops?characterEncoding=utf-8
    username: root
    password: Tv75aYT8@
    type: com.alibaba.druid.pool.DruidDataSource
  redis:
    #连接超时时间（毫秒）
    timeout: 30000
    database: 0
    host: 192.168.73.7
    port: 6379
    password:
    lettuce:
      pool:
        enabled: on
        #连接池最大连接数（使用负值表示没有限制）
        max-active: 8
        #连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1
        #连接池中的最大空闲连接
        max-idle: 8
        #连接池中的最小空闲连接
        min-idle: 0
mybatis-flex:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
