server:
  port: 18888
  shutdown: graceful
  servlet:
    encoding:
      force: true
      charset: UTF-8
      enabled: true
    context-path: /api/devops
  tomcat:
    uri-encoding: UTF-8

spring:
  profiles:
    active: dev
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  application:
    name: phenix-devops
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper.xml
  global-config:
    db-config:
      id-type: auto

